<h1>Artificial Neural Network</h1>

In [ ]:
# Artificial Neural Network

# Installing Theano
# pip install --upgrade --no-deps git+git://github.com/Theano/Theano.git

# Installing Tensorflow
# Install Tensorflow from the website: https://www.tensorflow.org/versions/r0.12/get_started/os_setup.html

# Installing Keras
# pip install --upgrade keras

# Part 1 - Data Preprocessing

# Importing the libraries
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

# Importing the dataset
dataset = pd.read_csv(r'C:\Users\...\Churn_Modelling.csv')
X = dataset.iloc[:, 3:13]
y = dataset.iloc[:, 13].values

In [2]:
dataset.head(10)

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,1,15634602,Hargrave,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,2,15647311,Hill,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,3,15619304,Onio,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,4,15701354,Boni,699,France,Female,39,1,0.00,2,0,0,93826.63,0
4,5,15737888,Mitchell,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0
5,6,15574012,Chu,645,Spain,Male,44,8,113755.78,2,1,0,149756.71,1
6,7,15592531,Bartlett,822,France,Male,50,7,0.00,2,1,1,10062.80,0
7,8,15656148,Obinna,376,Germany,Female,29,4,115046.74,4,1,0,119346.88,1
8,9,15792365,He,501,France,Male,44,4,142051.07,2,0,1,74940.50,0
9,10,15592389,H?,684,France,Male,27,2,134603.88,1,1,1,71725.73,0

In [3]:
# Encoding categorical data
from sklearn.preprocessing import LabelEncoder, OneHotEncoder

# dummy for Gender
labelencoder_X = LabelEncoder()
X.iloc[:,2] = labelencoder_X.fit_transform(X.iloc[:,2])

#dummy for Country
dummy_GEO = pd.get_dummies(X["Geography"])
X.drop("Geography", axis = 1, inplace=True)
dummy_GEO.drop(columns=['Spain'], inplace=True)
X = pd.concat([X, dummy_GEO], axis=1)
X[0:5]

,CreditScore,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,France,Germany
0,619,0,42,2,0.00,1,1,1,101348.88,1,0
1,608,0,41,1,83807.86,1,0,1,112542.58,0,0
2,502,0,42,8,159660.80,3,1,0,113931.57,1,0
3,699,0,39,1,0.00,2,0,0,93826.63,1,0
4,850,0,43,2,125510.82,1,1,1,79084.10,0,0

In [4]:
X=X.values
X[0:5]

array([[6.1900000e+02, 0.0000000e+00, 4.2000000e+01, 2.0000000e+00,
        0.0000000e+00, 1.0000000e+00, 1.0000000e+00, 1.0000000e+00,
        1.0134888e+05, 1.0000000e+00, 0.0000000e+00],
       [6.0800000e+02, 0.0000000e+00, 4.1000000e+01, 1.0000000e+00,
        8.3807860e+04, 1.0000000e+00, 0.0000000e+00, 1.0000000e+00,
        1.1254258e+05, 0.0000000e+00, 0.0000000e+00],
       [5.0200000e+02, 0.0000000e+00, 4.2000000e+01, 8.0000000e+00,
        1.5966080e+05, 3.0000000e+00, 1.0000000e+00, 0.0000000e+00,
        1.1393157e+05, 1.0000000e+00, 0.0000000e+00],
       [6.9900000e+02, 0.0000000e+00, 3.9000000e+01, 1.0000000e+00,
        0.0000000e+00, 2.0000000e+00, 0.0000000e+00, 0.0000000e+00,
        9.3826630e+04, 1.0000000e+00, 0.0000000e+00],
       [8.5000000e+02, 0.0000000e+00, 4.3000000e+01, 2.0000000e+00,
        1.2551082e+05, 1.0000000e+00, 1.0000000e+00, 1.0000000e+00,
        7.9084100e+04, 0.0000000e+00, 0.0000000e+00]])

In [5]:
# Splitting the dataset into the Training set and Test set
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)

In [6]:
# Feature Scaling
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [8]:
import tensorflow as tf

In [9]:
from tensorflow import keras

In [10]:
from tensorflow.keras import layers

In [12]:
# Importing the Keras libraries and packages

#Firstly, you should download and set up the anaconda via anaconda and then open anaconda prompt and then
#follow these steps via TensorFlow. Fourthly, you should use 'pip install --ignore-installed --upgrade tensorflow==1.14.0'
#to install TensorFlow 1.14 on Conda Finally, you can use TensorFlow that is version 1.14 on python 3.7
# OR visit this website:https://www.tensorflow.org/install/pip
#from keras.models import Sequential
from tensorflow.keras.layers import Dense

In [13]:
# Initialising the ANN
classifier = tf.keras.Sequential()

In [14]:
# Adding the input layer and the first hidden layer

classifier.add(layers.Dense(units = 6, kernel_initializer = 'uniform', activation = 'relu', input_dim = 11))

In [15]:
# Adding the second hidden layer
classifier.add(Dense(units = 6, kernel_initializer = 'uniform', activation = 'relu'))

In [16]:
# Adding the output layer
classifier.add(Dense(units = 1, kernel_initializer = 'uniform', activation = 'sigmoid'))

In [17]:
# Compiling the ANN
classifier.compile(optimizer = 'adam', loss = 'binary_crossentropy', metrics = ['accuracy'])

In [76]:
# Fitting the ANN to the Training set
classifier.fit(X_train, y_train, batch_size = 10, nb_epoch = 100)

WARNING:tensorflow:The `nb_epoch` argument in `fit` has been renamed `epochs`.
Train on 8000 samples
Epoch 1/100
8000/8000 [==============================] - 2s 285us/sample - loss: 0.4844 - accuracy: 0.7960
Epoch 2/100
8000/8000 [==============================] - 1s 181us/sample - loss: 0.4302 - accuracy: 0.7960
Epoch 3/100
8000/8000 [==============================] - 1s 180us/sample - loss: 0.4273 - accuracy: 0.7960
Epoch 4/100
8000/8000 [==============================] - 1s 163us/sample - loss: 0.4215 - accuracy: 0.8165
Epoch 5/100
8000/8000 [==============================] - 1s 166us/sample - loss: 0.4150 - accuracy: 0.8282
Epoch 6/100
8000/8000 [==============================] - 1s 177us/sample - loss: 0.4104 - accuracy: 0.8316
Epoch 7/100
8000/8000 [==============================] - 1s 177us/sample - loss: 0.4069 - accuracy: 0.8335
Epoch 8/100
8000/8000 [==============================] - 1s 178us/sample - loss: 0.4049 - accuracy: 0.8359
Epoch 9/100
8000/8000 [==============================] - 1s 175us/sample - loss: 0.4031 - accuracy: 0.8344
Epoch 10/100
8000/8000 [==============================] - 1s 187us/sample - loss: 0.4021 - accuracy: 0.8334
Epoch 11/100
8000/8000 [==============================] - 1s 166us/sample - loss: 0.4008 - accuracy: 0.8344
Epoch 12/100
8000/8000 [==============================] - 2s 193us/sample - loss: 0.4001 - accuracy: 0.8334
Epoch 13/100
8000/8000 [==============================] - 1s 169us/sample - loss: 0.3990 - accuracy: 0.8347
Epoch 14/100
8000/8000 [==============================] - 1s 183us/sample - loss: 0.3992 - accuracy: 0.8356
Epoch 15/100
8000/8000 [==============================] - 2s 201us/sample - loss: 0.3983 - accuracy: 0.8341
Epoch 16/100
8000/8000 [==============================] - 1s 186us/sample - loss: 0.3979 - accuracy: 0.8360
Epoch 17/100
8000/8000 [==============================] - 1s 166us/sample - loss: 0.3976 - accuracy: 0.8332
Epoch 18/100
8000/8000 [==============================] - 1s 176us/sample - loss: 0.3974 - accuracy: 0.8346
Epoch 19/100
8000/8000 [==============================] - 1s 171us/sample - loss: 0.3972 - accuracy: 0.8331
Epoch 20/100
8000/8000 [==============================] - 1s 180us/sample - loss: 0.3970 - accuracy: 0.8356
Epoch 21/100
8000/8000 [==============================] - 1s 156us/sample - loss: 0.3966 - accuracy: 0.8354
Epoch 22/100
8000/8000 [==============================] - 1s 154us/sample - loss: 0.3954 - accuracy: 0.8347
Epoch 23/100
8000/8000 [==============================] - 2s 199us/sample - loss: 0.3956 - accuracy: 0.8341
Epoch 24/100
8000/8000 [==============================] - 2s 206us/sample - loss: 0.3960 - accuracy: 0.8354
Epoch 25/100
8000/8000 [==============================] - 2s 196us/sample - loss: 0.3953 - accuracy: 0.8361
Epoch 26/100
8000/8000 [==============================] - 2s 225us/sample - loss: 0.3950 - accuracy: 0.8339
Epoch 27/100
8000/8000 [==============================] - 2s 218us/sample - loss: 0.3947 - accuracy: 0.8380
Epoch 28/100
8000/8000 [==============================] - 1s 171us/sample - loss: 0.3940 - accuracy: 0.8371
Epoch 29/100
8000/8000 [==============================] - 1s 161us/sample - loss: 0.3922 - accuracy: 0.8359
Epoch 30/100
8000/8000 [==============================] - 1s 170us/sample - loss: 0.3919 - accuracy: 0.8371
Epoch 31/100
8000/8000 [==============================] - 1s 167us/sample - loss: 0.3911 - accuracy: 0.8369
Epoch 32/100
8000/8000 [==============================] - 2s 213us/sample - loss: 0.3895 - accuracy: 0.8378
Epoch 33/100
8000/8000 [==============================] - 1s 155us/sample - loss: 0.3877 - accuracy: 0.8374
Epoch 34/100
8000/8000 [==============================] - 1s 165us/sample - loss: 0.3862 - accuracy: 0.8369
Epoch 35/100
8000/8000 [==============================] - 1s 150us/sample - loss: 0.3832 - accuracy: 0.8350
Epoch 36/100
8000/8000 [==============================] - 1s 154us/sample - loss: 0.3800 - accuracy: 0.8363
Epoch 37/100
8000/8000 [==============================] - 1s 166us/sample - loss: 0.3774 - accuracy: 0.8366
Epoch 38/100
8000/8000 [==============================] - 1s 187us/sample - loss: 0.3727 - accuracy: 0.8390
Epoch 39/100
8000/8000 [==============================] - 1s 184us/sample - loss: 0.3702 - accuracy: 0.8424
Epoch 40/100
8000/8000 [==============================] - 1s 179us/sample - loss: 0.3671 - accuracy: 0.8454
Epoch 41/100
8000/8000 [==============================] - 1s 178us/sample - loss: 0.3653 - accuracy: 0.8475
Epoch 42/100
8000/8000 [==============================] - 2s 201us/sample - loss: 0.3639 - accuracy: 0.8493
Epoch 43/100
8000/8000 [==============================] - 1s 181us/sample - loss: 0.3631 - accuracy: 0.8515
Epoch 44/100
8000/8000 [==============================] - 1s 180us/sample - loss: 0.3614 - accuracy: 0.8529
Epoch 45/100
8000/8000 [==============================] - 1s 169us/sample - loss: 0.3618 - accuracy: 0.8530
Epoch 46/100
8000/8000 [==============================] - 1s 170us/sample - loss: 0.3595 - accuracy: 0.8530
Epoch 47/100
8000/8000 [==============================] - 1s 168us/sample - loss: 0.3586 - accuracy: 0.8556
Epoch 48/100
8000/8000 [==============================] - 1s 185us/sample - loss: 0.3571 - accuracy: 0.8555
Epoch 49/100
8000/8000 [==============================] - 2s 216us/sample - loss: 0.3561 - accuracy: 0.8550
Epoch 50/100
8000/8000 [==============================] - 1s 164us/sample - loss: 0.3559 - accuracy: 0.8561
Epoch 51/100
8000/8000 [==============================] - 2s 226us/sample - loss: 0.3549 - accuracy: 0.8579
Epoch 52/100
8000/8000 [==============================] - 2s 256us/sample - loss: 0.3535 - accuracy: 0.8585
Epoch 53/100
8000/8000 [==============================] - 2s 192us/sample - loss: 0.3523 - accuracy: 0.8611
Epoch 54/100
8000/8000 [==============================] - 2s 188us/sample - loss: 0.3519 - accuracy: 0.8589
Epoch 55/100
8000/8000 [==============================] - 2s 286us/sample - loss: 0.3515 - accuracy: 0.8590
Epoch 56/100
8000/8000 [==============================] - 2s 245us/sample - loss: 0.3506 - accuracy: 0.8616
Epoch 57/100
8000/8000 [==============================] - 2s 286us/sample - loss: 0.3503 - accuracy: 0.8606
Epoch 58/100
8000/8000 [==============================] - 2s 298us/sample - loss: 0.3497 - accuracy: 0.8599
Epoch 59/100
8000/8000 [==============================] - 1s 175us/sample - loss: 0.3495 - accuracy: 0.8614
Epoch 60/100
8000/8000 [==============================] - 1s 178us/sample - loss: 0.3500 - accuracy: 0.8596
Epoch 61/100
8000/8000 [==============================] - 2s 220us/sample - loss: 0.3486 - accuracy: 0.8616
Epoch 62/100
8000/8000 [==============================] - 2s 218us/sample - loss: 0.3484 - accuracy: 0.8621
Epoch 63/100
8000/8000 [==============================] - 1s 183us/sample - loss: 0.3482 - accuracy: 0.8595
Epoch 64/100
8000/8000 [==============================] - 2s 224us/sample - loss: 0.3480 - accuracy: 0.8600
Epoch 65/100
8000/8000 [==============================] - 2s 250us/sample - loss: 0.3476 - accuracy: 0.8597
Epoch 66/100
8000/8000 [==============================] - 2s 280us/sample - loss: 0.3476 - accuracy: 0.8619
Epoch 67/100
8000/8000 [==============================] - 2s 243us/sample - loss: 0.3465 - accuracy: 0.8639
Epoch 68/100
8000/8000 [==============================] - 2s 249us/sample - loss: 0.3471 - accuracy: 0.8612
Epoch 69/100
8000/8000 [==============================] - 2s 269us/sample - loss: 0.3463 - accuracy: 0.8618
Epoch 70/100
8000/8000 [==============================] - 2s 271us/sample - loss: 0.3454 - accuracy: 0.8616
Epoch 71/100
8000/8000 [==============================] - 2s 275us/sample - loss: 0.3464 - accuracy: 0.8611
Epoch 72/100
8000/8000 [==============================] - 2s 311us/sample - loss: 0.3454 - accuracy: 0.8618
Epoch 73/100
8000/8000 [==============================] - 3s 363us/sample - loss: 0.3451 - accuracy: 0.8620
Epoch 74/100
8000/8000 [==============================] - 3s 367us/sample - loss: 0.3443 - accuracy: 0.8597
Epoch 75/100
8000/8000 [==============================] - 3s 341us/sample - loss: 0.3446 - accuracy: 0.8619
Epoch 76/100

8000/8000 [==============================] - 2s 278us/sample - loss: 0.3441 - accuracy: 0.8624
Epoch 77/100
8000/8000 [==============================] - 2s 282us/sample - loss: 0.3439 - accuracy: 0.8616
Epoch 78/100
8000/8000 [==============================] - 3s 331us/sample - loss: 0.3442 - accuracy: 0.8621
Epoch 79/100
8000/8000 [==============================] - 3s 337us/sample - loss: 0.3447 - accuracy: 0.8618
Epoch 80/100
8000/8000 [==============================] - 2s 188us/sample - loss: 0.3442 - accuracy: 0.8616
Epoch 81/100
8000/8000 [==============================] - 3s 342us/sample - loss: 0.3436 - accuracy: 0.8634
Epoch 82/100
8000/8000 [==============================] - 2s 244us/sample - loss: 0.3442 - accuracy: 0.8621
Epoch 83/100
8000/8000 [==============================] - 2s 309us/sample - loss: 0.3440 - accuracy: 0.8621
Epoch 84/100
8000/8000 [==============================] - 3s 344us/sample - loss: 0.3434 - accuracy: 0.8616
Epoch 85/100
8000/8000 [==============================] - 2s 238us/sample - loss: 0.3431 - accuracy: 0.8637
Epoch 86/100
8000/8000 [==============================] - 2s 203us/sample - loss: 0.3433 - accuracy: 0.8606
Epoch 87/100
8000/8000 [==============================] - 2s 188us/sample - loss: 0.3431 - accuracy: 0.8611
Epoch 88/100
8000/8000 [==============================] - 2s 204us/sample - loss: 0.3429 - accuracy: 0.8611
Epoch 89/100
8000/8000 [==============================] - 2s 224us/sample - loss: 0.3430 - accuracy: 0.8630
Epoch 90/100
8000/8000 [==============================] - 2s 255us/sample - loss: 0.3434 - accuracy: 0.8636
Epoch 91/100
8000/8000 [==============================] - 2s 262us/sample - loss: 0.3436 - accuracy: 0.8609
Epoch 92/100
8000/8000 [==============================] - 2s 305us/sample - loss: 0.3431 - accuracy: 0.8633
Epoch 93/100
8000/8000 [==============================] - 3s 382us/sample - loss: 0.3419 - accuracy: 0.8621
Epoch 94/100
8000/8000 [==============================] - 2s 288us/sample - loss: 0.3420 - accuracy: 0.8634
Epoch 95/100
8000/8000 [==============================] - 2s 216us/sample - loss: 0.3430 - accuracy: 0.8627
Epoch 96/100
8000/8000 [==============================] - 2s 221us/sample - loss: 0.3416 - accuracy: 0.8633
Epoch 97/100
8000/8000 [==============================] - 1s 186us/sample - loss: 0.3429 - accuracy: 0.8624
Epoch 98/100
8000/8000 [==============================] - 2s 235us/sample - loss: 0.3431 - accuracy: 0.8609
Epoch 99/100
8000/8000 [==============================] - 2s 238us/sample - loss: 0.3424 - accuracy: 0.8620
Epoch 100/100
8000/8000 [==============================] - 2s 209us/sample - loss: 0.3423 - accuracy: 0.8610

In [85]:
# Part 3 - Making the predictions and evaluating the model

# Predicting the Test set results
y_pred = classifier.predict(X_test)
y_pred = (y_pred > 0.5)
y_pred[0:6]

array([[False],
       [False],
       [False],
       [False],
       [False],
       [ True]])

In [83]:

# Making the Confusion Matrix
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred)
cm

array([[1504,   91],
       [ 191,  214]], dtype=int64)